<template><div><h1 id="gif" tabindex="-1"><a class="header-anchor" href="#gif" aria-hidden="true">#</a> GIF</h1>
<AnimationGif /><div class="language-vue line-numbers-mode" data-ext="vue"><pre v-pre class="language-vue"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>template</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>ol-map</span> <span class="token attr-name">ref</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>map<span class="token punctuation">"</span></span> <span class="token punctuation">/></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>template</span><span class="token punctuation">></span></span>

<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>script</span><span class="token punctuation">></span></span><span class="token script"><span class="token language-javascript">
<span class="token keyword">import</span> <span class="token string">'gifler'</span>
<span class="token keyword">import</span> OlMap <span class="token keyword">from</span> <span class="token string">'./InitMap.vue'</span>
<span class="token keyword">import</span> Feature <span class="token keyword">from</span> <span class="token string">'ol/Feature.js'</span>
<span class="token keyword">import</span> Point <span class="token keyword">from</span> <span class="token string">'ol/geom/Point.js'</span>

<span class="token comment">// 图层</span>
<span class="token keyword">import</span> <span class="token punctuation">{</span> Vector <span class="token keyword">as</span> VectorSource <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'ol/source.js'</span>
<span class="token keyword">import</span> <span class="token punctuation">{</span> Vector <span class="token keyword">as</span> VectorLayer <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'ol/layer.js'</span>
<span class="token comment">// 样式</span>
<span class="token keyword">import</span> <span class="token punctuation">{</span> Style<span class="token punctuation">,</span> Icon <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'ol/style.js'</span>

<span class="token keyword">export</span> <span class="token keyword">default</span> <span class="token punctuation">{</span>
    <span class="token literal-property property">components</span><span class="token operator">:</span> <span class="token punctuation">{</span>
        OlMap<span class="token punctuation">,</span>
    <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token function">data</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token punctuation">{</span>
            <span class="token literal-property property">_map</span><span class="token operator">:</span> <span class="token keyword">null</span><span class="token punctuation">,</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token function">mounted</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">this</span><span class="token punctuation">.</span>$data<span class="token punctuation">.</span>_map <span class="token operator">=</span> <span class="token keyword">this</span><span class="token punctuation">.</span>$refs<span class="token punctuation">.</span>map<span class="token punctuation">.</span><span class="token function">getMap</span><span class="token punctuation">(</span><span class="token punctuation">)</span>

        <span class="token keyword">this</span><span class="token punctuation">.</span><span class="token function">addPointGif</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token number">14203335.093542054</span><span class="token punctuation">,</span> <span class="token number">5428667.749246727</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token string">'gif/dog_dance.gif'</span><span class="token punctuation">)</span>
        <span class="token keyword">this</span><span class="token punctuation">.</span><span class="token function">addPointGif</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token number">14143335.093542054</span><span class="token punctuation">,</span> <span class="token number">5480667.749246727</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token string">'gif/dog_cheer.gif'</span><span class="token punctuation">)</span>
        <span class="token keyword">this</span><span class="token punctuation">.</span><span class="token function">addPointGif</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token number">14263335.093542054</span><span class="token punctuation">,</span> <span class="token number">5480667.749246727</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token string">'gif/dog_cheer.gif'</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token literal-property property">methods</span><span class="token operator">:</span> <span class="token punctuation">{</span>
        <span class="token function">addPointGif</span><span class="token punctuation">(</span><span class="token parameter">coordinates<span class="token punctuation">,</span> path</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token keyword">const</span> iconFeature <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Feature</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
                <span class="token literal-property property">geometry</span><span class="token operator">:</span> <span class="token keyword">new</span> <span class="token class-name">Point</span><span class="token punctuation">(</span>coordinates<span class="token punctuation">)</span><span class="token punctuation">,</span>
            <span class="token punctuation">}</span><span class="token punctuation">)</span>

            <span class="token keyword">const</span> vectorSource <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">VectorSource</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
                <span class="token literal-property property">features</span><span class="token operator">:</span> <span class="token punctuation">[</span>iconFeature<span class="token punctuation">]</span><span class="token punctuation">,</span>
            <span class="token punctuation">}</span><span class="token punctuation">)</span>

            <span class="token keyword">const</span> vectorLayer <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">VectorLayer</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
                <span class="token literal-property property">source</span><span class="token operator">:</span> vectorSource<span class="token punctuation">,</span>
            <span class="token punctuation">}</span><span class="token punctuation">)</span>
            window<span class="token punctuation">.</span><span class="token function">gifler</span><span class="token punctuation">(</span>path<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">frames</span><span class="token punctuation">(</span>
                document<span class="token punctuation">.</span><span class="token function">createElement</span><span class="token punctuation">(</span><span class="token string">'canvas'</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
                <span class="token punctuation">(</span><span class="token parameter">ctx<span class="token punctuation">,</span> frame</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
                    <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span>iconFeature<span class="token punctuation">.</span><span class="token function">getStyle</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
                        iconFeature<span class="token punctuation">.</span><span class="token function">setStyle</span><span class="token punctuation">(</span>
                            <span class="token keyword">new</span> <span class="token class-name">Style</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
                                <span class="token literal-property property">image</span><span class="token operator">:</span> <span class="token keyword">new</span> <span class="token class-name">Icon</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
                                    <span class="token literal-property property">img</span><span class="token operator">:</span> ctx<span class="token punctuation">.</span>canvas<span class="token punctuation">,</span>
                                    <span class="token literal-property property">imgSize</span><span class="token operator">:</span> <span class="token punctuation">[</span>frame<span class="token punctuation">.</span>width<span class="token punctuation">,</span> frame<span class="token punctuation">.</span>height<span class="token punctuation">]</span><span class="token punctuation">,</span>
                                    <span class="token literal-property property">opacity</span><span class="token operator">:</span> <span class="token number">0.8</span><span class="token punctuation">,</span>
                                <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
                            <span class="token punctuation">}</span><span class="token punctuation">)</span>
                        <span class="token punctuation">)</span>
                    <span class="token punctuation">}</span>
                    ctx<span class="token punctuation">.</span><span class="token function">clearRect</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> frame<span class="token punctuation">.</span>width<span class="token punctuation">,</span> frame<span class="token punctuation">.</span>height<span class="token punctuation">)</span>
                    ctx<span class="token punctuation">.</span><span class="token function">drawImage</span><span class="token punctuation">(</span>frame<span class="token punctuation">.</span>buffer<span class="token punctuation">,</span> frame<span class="token punctuation">.</span>x<span class="token punctuation">,</span> frame<span class="token punctuation">.</span>y<span class="token punctuation">)</span>
                    <span class="token keyword">this</span><span class="token punctuation">.</span>$data<span class="token punctuation">.</span>_map<span class="token punctuation">.</span><span class="token function">render</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
                <span class="token punctuation">}</span><span class="token punctuation">,</span>
                <span class="token boolean">true</span>
            <span class="token punctuation">)</span>
            <span class="token keyword">this</span><span class="token punctuation">.</span>$data<span class="token punctuation">.</span>_map<span class="token punctuation">.</span><span class="token function">addLayer</span><span class="token punctuation">(</span>vectorLayer<span class="token punctuation">)</span>
        <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token punctuation">}</span>
</span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>script</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


